GET http://localhost:3000/to-do-list

###

POST http://localhost:3000/to-do-list/to-do/new
Content-Type: application/json

{
  "text": "Go to work"
}

###

PATCH http://localhost:3000/to-do-list/edit/64ccee2468ac01e6f0f451fc
Content-Type: application/json

{
  "text": "Make projects!"
}

###

PUT http://localhost:3000/to-do-list/complete/64ccee2468ac01e6f0f451fc

###

DELETE http://localhost:3000/to-do-list/delete/64ccf165396bb848594f9120